# Generated by Django 4.2.6 on 2023-10-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='efforts',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
