# Generated by Django 4.2.6 on 2023-10-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_task_efforts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='efforts',
            field=models.IntegerField(default=2),
        ),
    ]
